### PR TITLE
Change dev dependencies

### LINKED ISSUE #18: Update dev dependencies
Resolve the following: 
image

### PR DESCRIPTION
**Pull request by arturparkhisenko**
Changelog:
- Changed dev dependencies to the latest
- Changed yarn.lock file
- Removed package-lock file, it's unused and not used by the [CI/Test](https://github.com/SeanMcP/a11y-react-emoji/blob/master/.circleci/config.yml) env 

Closes #18

And as a part of the Hacktoberfest month, I would appreciate and like to ask you to add all the necessary labels(tags), please.
It is `hacktoberfest` topic to the repository, and `hacktoberfest-accepted` if PR was accepted. 

## Audit

image

### CODE REVIEW

**Comment by SeanMcP** [comment]
@arturparkhisenko Can you please provide a screen shot of `npm audit` in the PR description?

**Comment by arturparkhisenko** [comment]
@SeanMcP yes, tho I see why we had a package-lock file, we did use yarn on CI and release, but `npm audit` requires the original npm lock-file. I did run install, and this the result is attached. Yarn `yarn audit` says 0 critical but it mentions other categories for the Jest test dependency.

npm-audit-2020-10-19

**Comment by SeanMcP** [comment]
Since this package doesn't have any non-dev dependencies, I'm not too worried about having both lock files or generating a `package-lock.json` for audits.

**Review by SeanMcP — CHANGES_REQUESTED** [review]
@arturparkhisenko Could you add a link to `CHANGELOG.md` under "Changed" for "Updated dev dependencies"? I don't think we need to be more explicit than that.

**Comment by arturparkhisenko** [comment]
@SeanMcP Added it. It was required to force-push after rebase because the branch was created before the previous PR with the changelog was merged.

**Review by SeanMcP — APPROVED** [review]
Looks good! Thanks for adding those changes.

**Comment by SeanMcP** [comment]
Addressed in #26

**Pull request closed without merging**
